[project]
name = "neb"
version = "0.1.0"
description = "Seek the real power of AI agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-ai>=0.0.35",
    "rtoml>=0.12.0",
]
